### ISSUE TITLE
Is there a way to change IP address of the Rest Manager from localhost to some other ip address ?

### ISSUE THREAD

**Issue by shashikr88** [universAAL/remote#482]
Hallo,

I am running universaal on a VM server. The problem is by default it is always running on 127.0.0.1:9000. I did check try to change system.properties (added the line org.universAAL.ri.rest.manager.serv.host="http://xxx.xx.xx.xx:9000" ) under distro.karaf/etc folder as per the Rest documentation. But still nothing changes when I start the rest manger.

Thanks

**Comment by amedranogil** [comment]
which version of universAAL are you using?
This was recently fixed, so it might only be available in version 3.4.2-SNAPSHOT (Development version)

**Comment by shashikr88** [comment]
Oh ok thanks. I am currently using karaf version 3.0.5.
