### ISSUE TITLE
[ri.api.manager] Set default dir for RAPIPersistence to confadmin subdir

### ISSUE THREAD

**Issue by cstockloew** [universAAL/remote#5]
If the sys prop "org.universAAL.ri.api.manager.db.path" is not set, the default dir is /RAPIPersistence, so it's in root dir of the hdd. This should be changed to be
`ModuleContext.getDataFolder() + "/RAPIPersistence"`
I guess, it should be getDataFolder and not getConfigHome?

**Comment by Alfiva** [comment]
Changed in a1a1ba2 . Existing executions using the Remote API and RESTAPI should change their config files if they want to keep their existing DB: Just change org.universAAL.ri.api.manager.db.path or org.universAAL.ri.rest.manager.db.path property to /RAPIPersistence or /RESTPersistence respectively.
