### ISSUE TITLE
Configure address and port in REST manager

### ISSUE THREAD

**Issue by Alfiva** [universAAL/remote#6]
Right now the address and port in REST manager are hardcoded to localhost:9000 which is not practical, and in some cases not even functional. Change the behaviour so that this can be configured through properties like everything else.

**Comment by Alfiva** [comment]
Done in c8a88507b0a2e34e5916a6d333c9bf1b99e0ac18

**Comment by amedranogil** [comment]
issue still reported in #482

**Comment by Alfiva** [comment]
But then closed
